queue_rules:
  - name: default
    merge_conditions:
      - check-success=Build docker-pid
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label=merge-queue
    actions:
      queue: {}
