language: go
go:
  - 1.10
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
