name: Build
on:
  push:
  pull_request:
jobs:
  build:
    name: Build docker-pid
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.4
      with:
        go-version: '1.15.6'
    - name: Build
      run: go build .
